Simple compatibility on Windows
jamiestraw/streaker pull request #9
Opened 2018-09-15 09:12 UTC by KeziahMoselle

Hello,

This looked great but i'm on Windows so I cannot launch it and try to make it run.

This is my first PR, please be gentle.

- [x] White icons
- [x] Exported the white icons for Windows
- [x] Fix error on the main process (app.dock.hide();)

2018-09-15 12:55 UTC, jamieweavis commented
Thanks for the pull request @KeziahMoselle! I'm on holiday at the moment but I'll look at getting this merged when I'm back in a few days 👍

2018-09-16 14:01 UTC, KeziahMoselle commented
After `npx build` on Windows and installed Streaker, Streaker don't launch automatically at login.
I have no clue how to fix that.

2018-09-16 14:22 UTC, KeziahMoselle commented
Okay, probably need to change the path here : 
```js
const streakerAutoLauncher = new AutoLaunch({
    name: pjson.name,
    path: `/Applications/${pjson.name}.app`
  });
```
I will try to fix that soon.

2018-09-16 17:36 UTC, KeziahMoselle commented
The weird [] was the tabulation \t at :
```js
{ label: `Current Streak:\t${currentStreak}`, enabled: false },
{ label: `Best Streak:\t\t${bestStreak}`, enabled: false },
{ label: `Contributions:\t${contributionCount}`, enabled: false },
```
When I removed them, the [] disappear : 
![preview](https://puu.sh/Bw0MW/0fe127c11d.png)

2018-09-21 11:55 UTC, jamieweavis requested changes

2018-09-21 11:55 UTC, jamieweavis commented on src/app.js
> +  if (process.platform == 'darwin') {
Could we please use strict equality checks? e.g. `process.platform === 'darwin'`

2018-09-21 11:55 UTC, jamieweavis commented on src/icon.js
> +if (process.platform == 'win32') {
Again, strict equality checks please! Your editor/IDE should be complaining about this if it has eslint integration.

2018-09-21 11:55 UTC, jamieweavis commented on src/icon.js
> +    done: path.join(__dirname, 'icons/win/doneTemplate.png'),
Icons only need to be suffixed with `Template` on macOS, this is for light and dark mode support - for Windows we can remove them.

I noticed that the tray icons look quite pixelated in your screenshot, according to the [Electron docs](https://electronjs.org/docs/api/tray#class-tray):
> On Windows it is recommended to use ICO icons to get best visual effects.

2018-09-30 11:01 UTC, jamieweavis approved these changes

2018-09-30 11:20 UTC, jamieweavis requested changes
Sorry for the delay, I've been quite busy lately.

Thanks for sorting out the icon, looking much better now!

Regarding the tabulation, I think we can safely remove it since it feels a little hacky and I'm not sure it adds any value anyway - in the future we could perhaps look at having the numbers aligned all the way to the right of the menu but that's out of scope of this issue.

As you found out, the autolauncher path will need updating depending on which platform we're on. The [auto-launch](https://github.com/Teamwork/node-auto-launch) package that we are using already supports Windows so it should just be a case of using the correct path when on Windows - it looks like the Windows installer installs to the path: `C:\Users\me\AppData\Local\Programs\Streaker`.

Once these two points have been addressed then this should be ready to merge!

2018-09-30 13:10 UTC, KeziahMoselle commented
Yeah look's better !
![preview.png](https://puu.sh/BDowj/224ce6881d.png)
I removed the \t and remove the path option, according to the docs : 
> For NW.js and Electron apps, you don't have to specify the path. We guess based on `process.execPath`.
And it works !

2018-09-30 13:22 UTC, KeziahMoselle commented
I tested it on my MacBook and it works too, without the `path` field

2018-10-01 12:18 UTC, jamieweavis approved these changes

2018-10-01 12:19 UTC, jamieweavis commented
Fantastic, thanks for this!

2018-10-01 12:19 UTC, merged